POST https://e-consulta.sunat.gob.pe/cl-at-ittipcam/tcS01Alias/listarTipoCambio
Content-Type: application/json

{
  "anio": 2024,
  "mes": 1,
  "token": "03AFcWeA7Y_wDUwV2ddrhZ_R6g-NhtF9lBbPSXeykXgo5CfF3_8u4gKfCUHkoVlkGFFNuejJuGgpFzWE8BToS7bhli1yKfKCQHkHoZtlRMJZsqzbIzfD9tRlPuBV6BhvGcKmek94i93Khi-m2Qvi9eOJX_1G9o0U6adM0IGJVqKwtmaNxkguu0tWUXmEYQC96ScRPcnse1ui0sWJAtx7RdYmg8cOrPsClL4BQj8sQ5pVgwpDEeY_iyOjNn1EYIXAG77YmWE6ggAgX4tYJyhyVvpLKkMCDTh7tmYpcKpilQ8mQlk36dKp3gRQpmTcPy8aYFoKaHS2awQZeTBufo2aPzHKZRltu7CFmWeMsxZFgxmk1tbKTf4y3-5l4MjwWxTI2T8U_YCdn9zy7Btn2ndoPJ0AJKsoGSl-RXDqAgr6FWcBrWGoLjIXHgRFXZWFgOuopMX2h-A9iMr6w04KMwFylAl-M2jWmVdyjF6uKpeFy3Rp-WPPl8y5IQsr2bUSMWSAWBENUllX5d2PtUP7Qxd13s9uKr-WSMpLfno5aVniXSlPQCxS5Mx_eBiJhQEwu24G37DcbSbaTHbU8LOCC-dOzAbc6kCth4wBh8VNoQhNO41hmBSFcuNkBIHDoKl-TvYUk9raweXZ4ajp-x14jSjMwg26dge8VEEOB0mclY88wsdVt3g3b3Jkg_8Jg"
}
